version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=${ENV}
      - PAT=${PAT}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - LOG_LEVEL=info

  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./web_interface:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - fastapi
