# Build pipeline for the project
name: Build
on:
  workflow_call:
    inputs:
      ARTIFACT-NAME:
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [fastapi, streamlit]
        path: [docker/fastapi/Dockerfile, docker/streamlit/Dockerfile]
        exclude:
          - service: streamlit
            path: docker/fastapi/Dockerfile
          - service: fastapi
            path: docker/streamlit/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.DOCKER_REGISTRY_URL}}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME}}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD}}

      - name: Create tag from commit SHA
        run: |
          export VERSION:$(git rev-parse --short HEAD | cut -c1-7)
          echo "VERSION_TAG=${VERSION}" >> $GITHUB_ENV

      - name: Build and Push Docker FastAPI image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.path }}
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_URL }}/${{ github.event.repository.name }}/${{ matrix.service }}:${{ env.VERSION_TAG }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.ARTIFACT-NAME }}
          path: operations/
