name: Percival
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    uses: ./github/workflows/build.yaml@main
    secrets: inherit
    with:
      ARTIFACT-NAME: pervical-artifact

  deploy:
    name: Deploy
    uses: ./github/workflows/deploy.yaml@main
    needs: build
    secrets: inherit
    with:
      ENVIRONMENT-CODE: tst01
      REGION-CODE: sea
      ARTIFACT-NAME: pervical-artifact
