name: Deploy Template

on:
  workflow_call:
    inputs:
      ARTIFACT-NAME:
        required: true
        type: string
      ENVIRONMENT-CODE:
        required: true
        type: string
      REGION-CODE:
        required: true
        type: string
jobs:
  deploy:
    env:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      BACKEND_CONFIG_PATH: "${{ github.workspace }}/operations/config"
      VARIABLE_FILE_PATH: "${{ github.workspace }}/operations/variables"
      TF_PATH: "${{ github.workspace }}/operations/provision"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.ARTIFACT-NAME }}
          path: operations/

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.ARTIFACT-NAME }}
          path: operations/

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ vars.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "subscriptionId": "${{ vars.ARM_SUBSCRIPTION_ID }}" ,"tenantId": "${{ vars.ARM_TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        run: terraform init -input=false -backend-config="${{ env.BACKEND_CONFIG_PATH }}/backend.${{ inputs.ENVIRONMENT-CODE }}.${{ inputs.REGION-CODE }}.conf"
        working-directory: "${{ env.TF_PATH}}"

      - name: Terraform validate
        if: ${{ github.ref_name != 'refs/heads/main' }}
        run: terraform validate
        working-directory: "${{ env.TF_PATH}}"

      - name: Terraform plan
        run: terraform plan -out="tfplan-percival" -input=false -no-color -var-file="${{ env.VARIABLE_FILE_PATH }}/variables.${{ inputs.ENVIRONMENT-CODE }}.${{ inputs.REGION-CODE }}.tfvars"
        working-directory: "${{ env.TF_PATH}}"
      
      - name: Terraform apply
        run: terraform apply -input=false -no-color tfplan-percival
        continue-on-error: true
        working-directory: "${{ env.TF_PATH}}"

      # - name: Deploy FastAPI Container app
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     acrName: ${{ inputs.ACR-NAME}}
      #     imageToDeploy: ${{ vars.DOCKER-REGISTRY-URL }}/${{ github.event.repository.name }}/fastapi:${{ env.VERSION_TAG }}
      #     containerAppName: ${{ inputs.CONTAINER-APP-NAME }}
      #     resourceGroup: ${{ inputs.RESOURCE-GROUP }}
      #     containerAppEnvironment: ${{ inputs.ENVIRONMENT-CODE }}

      # - name: Deploy Streamlit Container app
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     acrName: ${{ inputs.ACR-NAME}}
      #     imageToDeploy: ${{ vars.DOCKER-REGISTRY-URL }}/${{ github.event.repository.name }}/streamlit:${{ env.VERSION_TAG }}
      #     containerAppName: ${{ inputs.CONTAINER-APP-NAME }}
      #     resourceGroup: ${{ inputs.RESOURCE-GROUP }}
      #     containerAppEnvironment: ${{ inputs.ENVIRONMENT-CODE }}
